plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}" apply false
}

allprojects {
    group = project.maven_group
    repositories {
        maven { name = 'Fabric'; url = 'https://maven.fabricmc.net/' }
        mavenCentral()
        maven { name = 'Shedaniel'; url = 'https://maven.shedaniel.me/' }
        maven { name = 'Modrinth'; url = 'https://api.modrinth.com/maven' }
    }
}

subprojects {
    apply plugin: 'net.fabricmc.fabric-loom'
    apply plugin: 'java-library'

    base {
        archivesName = project.name == 'core' ? 'herbcraft' : "herbcraft-${project.name}"
    }

    version = '1.0.0'

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        implementation "net.fabricmc:fabric-loader:${rootProject.loader_version}"
        implementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    }

    if (project.name == 'core') {
        dependencies {
            compileOnly "maven.modrinth:jade:26.2.9+fabric"
            runtimeOnly "maven.modrinth:jade:26.2.9+fabric"
        }
    }

    if (project.name == 'alchemy' || project.name == 'cuisine') {
        dependencies { implementation project(':core') }
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = 25
        options.encoding = 'UTF-8'
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
        withSourcesJar()
    }

    jar {
        from(rootProject.file('LICENSE')) { rename { "${it}_${project.name}" } }
    }
}
